Upgrade to BeautifulSoup version 4
Installing beautifulsoup with python 3's pip fails with...

  You're trying to run a very old release of Beautiful Soup under Python 3.
  This will not work."<>"Please use Beautiful Soup 4, available through the pip
  package 'beautifulsoup4'.

Attempting to use this as a drop-in replacement. Initially importing bs4 failed
with...

  >>> import bs4
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
      from .builder import builder_registry, ParserRejectedMarkup
    File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
      from . import _html5lib
    File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
      class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
  AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

Upgrading to a specific version of html5lib as per the following fixed this...

  https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base

Test results unchanged...

  before: FAILED (skips=6, failures=9, errors=194, successes=359)
  after:  FAILED (skips=6, failures=9, errors=194, successes=359)