Fix moat test
Trivial byte hiccup...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_distributors_moat_server.py", line 183, in test_formatDataForResponse_no_data
      rendered = self.resource.formatDataForResponse(None, request)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/distributors/moat/server.py", line 182, in formatDataForResponse
      request.responseHeaders.addRawHeader(b"Server", b"moat/%s" % MOAT_API_VERSION)
  builtins.TypeError: %b requires bytes, or an object that implements __bytes__, not 'str'

Test results changed as follows...

  before: FAILED (skips=114, failures=16, errors=76, successes=778)
  after:  FAILED (skips=114, failures=21, errors=57, successes=792)