Convert generators to lists
Python 3 changes several builtins to provide generators rather than lists. This
is more efficient, but means we need to convert to a list to be indexable.

There will likely be more instances down the road, but fixing all the instances
that are immediately evedant in the test output. This fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_proxy.py", line 355, in test_ProxySet_addProxies_tuple_individual_tags
      self.assertEquals(len(self.proxyList), len(self.proxies) + len(extraProxies))
  builtins.TypeError: object of type 'zip' has no len()

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_parse_headers.py", line 47, in test_addNonLocalizedVariant
      langs = headers.parseAcceptLanguage(header)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/parse/headers.py", line 70, in parseAcceptLanguage
      placement = langs.index(insertAfter[0]) + 1
  builtins.TypeError: 'filter' object is not subscriptable

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_bridges.py", line 895, in setUp
      self._parseAllDescriptorFiles()
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_bridges.py", line 852, in _parseAllDescriptorFiles
      self._extrainfoFile).values()[0]
  builtins.TypeError: 'dict_values' object does not support indexing

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_bridges.py", line 315, in test_integration_getConfigLine_scramblesuit_withFingerprint
      transport='scramblesuit')
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 847, in getConfigLine
      bridgeLine = self.getBridgeLine(bridgeRequest, includeFingerprint)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1362, in getBridgeLine
      pt = self._getTransportForRequest(bridgeRequest)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1196, in _getTransportForRequest
      return transports[position % len(unblocked)]
  builtins.TypeError: 'filter' object is not subscriptable

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_Bridges.py", line 78, in test_filterDistinctSubnets_random_bridges
      chosen = self.ring.bridges.keys()[:3]
  builtins.TypeError: 'dict_keys' object is not subscriptable

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_Bridges.py", line 65, in test_filterDistinctSubnets
      chosen = self.ring.bridges.keys()[:10]
  builtins.TypeError: 'dict_keys' object is not subscriptable

Test results changed as follows...

  before: FAILED (skips=114, failures=13, errors=191, successes=663)
  after:  FAILED (skips=114, failures=14, errors=158, successes=695)