Fix txcaptcha tests
The _encodeIfNecessary() helper didn't make sense. It claimed to encode unicode
into unicode whereas what it really did was simply normalizing inputs to bytes.

I tested urlencode() with a mixture of unicode/bytes and it normalizes its
inputs so this helper doesn't do anything. This fixes...

	Traceback (most recent call last):
  	File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_txrecaptcha.py", line 274, in test_encodeIfNecessary
    	self.assertIsInstance(origString, unicode)
	builtins.NameError: name 'unicode' is not defined

Test results changed as follows...

  before: FAILED (skips=109, failures=18, errors=386, successes=468)
  after:  FAILED (skips=109, failures=18, errors=383, successes=470)