Replace basestring with str
Python 3.x does not have a basestring class...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_parse_addr.py", line 277, in test_isIPAddress_IP4DefaultRoute
      self.runTestForAddr(IP4DefaultRoute)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_parse_addr.py", line 225, in runTestForAddr
      result = addr.isIPAddress(testAddress)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/parse/addr.py", line 314, in isIPAddress
      if isValidIP(ip):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/parse/addr.py", line 410, in isValidIP
      if isinstance(ip, basestring):
  builtins.NameError: name 'basestring' is not defined

Some replacement might *not* work. To be fully a drop-in replacement instead
have...

  python 2: isisntance(msg, basestring)
  python 3: isinstance(msg, (str, bytes))

... however, many of these code paths would break if they received a bytes
rather than a unicode object. Porting to python 3.x requires that we play less
fast and loose with byte/unicode typing so I'm going to presume 'bytes => str
(unicode)' for our initial porting then fix required normalizations as we go
along.

Test outcome changes as follows...

  before: FAILED (failures=5, errors=138, successes=164)
  after:  FAILED (skips=1, failures=3, errors=61, successes=242)