Remove old buffer handling
Honestly I'm confused what isis was attempting to do here. This has something
to do with old python version compatability so it's likely moot.

Python 3.x replaced buffer() with memoryview()...

  https://stackoverflow.com/questions/50160187/buffer-function-for-python-3

... so we could likely could make that replacement. But instead lets try to
simply rip this out.

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 823, in loadByName
      return self.suiteFactory([self.findByName(name, recurse=recurse)])
    ...
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridgerequest.py", line 27, in <module>
      from bridgedb.crypto import getHMACFunc
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/crypto.py", line 74, in <module>
      io.BytesIO(buffer('test'))
  builtins.NameError: name 'buffer' is not defined

This didn't change test outcome...

  before: FAILED (skips=1, failures=7, errors=48, successes=256)
  after:  FAILED (skips=1, failures=7, errors=48, successes=256)