Normalize getHMAC inputs
Calculating the hmac requires bytes. This fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_https_distributor.py", line 152, in test_HTTPSDistributor_prepopulateRings_without_proxies
      dist = distributor.HTTPSDistributor(3, self.key)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/distributors/https/distributor.py", line 93, in __init__
      key2 = getHMAC(key, "Assign-Bridges-To-Rings")
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/crypto.py", line 193, in getHMAC
      h = hmac.new(key, value, digestmod=DIGESTMOD)
    File "/usr/lib/python3.5/hmac.py", line 144, in new
      return HMAC(key, msg, digestmod)
    File "/usr/lib/python3.5/hmac.py", line 42, in __init__
      raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
  builtins.TypeError: key: expected bytes or bytearray, but got 'str'

Test results changed as follows...

  before: FAILED (skips=109, failures=22, errors=318, successes=531)
  after:  FAILED (skips=109, failures=21, errors=283, successes=567)