Replace has_key method call
Python's has_key method was always pointless since "x in my_dict" does the
same. The method was removed in python 3 so this fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_https_distributor.py", line 255, in test_HTTPSDistributor_getBridges_with_varied_blocked_bridges
      bridge.setBlockedIn('cn', methodname='vanilla')
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1501, in setBlockedIn
      self._addBlockByKey(key, countryCode)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1381, in _addBlockByKey
      if self._blockedIn.has_key(key):
  builtins.AttributeError: 'dict' object has no attribute 'has_key'

Test results changed as follows...

  before: FAILED (skips=114, failures=15, errors=140, successes=716)
  after:  FAILED (skips=114, failures=15, errors=133, successes=723)