Fix minor type issues
Just some instances of low hanging fruit...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_Bridges.py", line 110, in test_dumpAssignments
      first = self.ring.bridges.values()[0].fingerprint
  builtins.TypeError: 'dict_values' object does not support indexing

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_parse_headers.py", line 37, in test_defaultTBBHeader
      self.assertIsInstance(langs, list)
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/_synctest.py", line 649, in assertIsInstance
      instance, classOrTuple, suffix))
  twisted.trial.unittest.FailTest: <map object at 0x7f986ca07ba8> is not an instance of <class 'list'>

Test results changed as follows...

  before: FAILED (skips=115, failures=29, errors=3, successes=837)
  after:  FAILED (skips=115, failures=27, errors=2, successes=840)