Fix metric test
Just the normal unicode/byte issue. This fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_metrics.py", line 164, in test_email_metrics
      email_metrix.recordValidEmailRequest(responder)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/metrics.py", line 411, in recordValidEmailRequest
      self._recordEmailRequest(smtpAutoresp, True)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/metrics.py", line 403, in _recordEmailRequest
      sld = emailAddr.domain.split(".")[0]
  builtins.TypeError: a bytes-like object is required, not 'str'

Test results mostly unchanged...

  before: FAILED (skips=114, failures=15, errors=109, successes=747)
  after:  FAILED (skips=114, failures=16, errors=108, successes=747)