Read router status entries as bytes
Stem expects descriptors to be bytes. This fixes the following errors...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_parse_descriptors.py", line 392, in test_parse_descriptors_parseNetworkStatusFile_bad_nickname
    ...
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/parse/descriptors.py", line 135, in parseNetworkStatusFile
      routers.extend(list(document))
    File "/usr/local/lib/python3.5/dist-packages/stem/descriptor/router_status_entry.py", line 101, in _parse_file
      desc_content = bytes.join(b'', desc_lines)
  builtins.TypeError: sequence item 0: expected a bytes-like object, str found

Just fixing that caused the tests to hang due to an infinite loop in descriptor
parsing. Unsure why Isis implemented it that way so simply pulling that out.

Test results changed as follows...

  before: FAILED (skips=103, failures=9, errors=189, successes=366)
  after:  FAILED (skips=103, failures=6, errors=183, successes=375)