Replace usage of unicode function
In most cases unicode() is being called on static strings that are already
unicode in python 3.x. In the few instances where these actually seem to
attempt normalization the proper way to convert bytes is
"my_bytes.decode('utf-8')".

This fixes the following exceptions...

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 823, in loadByName
      return self.suiteFactory([self.findByName(name, recurse=recurse)])
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 702, in findByName
      __import__(name)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_persistentSaveAndLoad.py", line 31, in <module>
      TEST_CONFIG_FILE = io.StringIO(unicode("""\
  builtins.NameError: name 'unicode' is not defined

Test results change as follows...

  before: FAILED (skips=106, failures=6, errors=182, successes=375)
  after:  FAILED (skips=106, failures=16, errors=273, successes=409)