Error concatenating range with a list
BridgeDB relies on catch-alls to address its underlying buginess, which is
making this harder. Removed one to uncover our http_server's actual
exception...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_https_server.py", line 740, in test_renderAnswer_GET_textplain_malicious
      page = self.bridgesResource.render(request)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/distributors/https/server.py", line 920, in render
      response = self.getBridgeRequestAnswer(request)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/distributors/https/server.py", line 967, in getBridgeRequestAnswer
      bridgeRequest, self.includeFingerprints)) for bridge in bridges]
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/distributors/https/server.py", line 967, in <listcomp>
      bridgeRequest, self.includeFingerprints)) for bridge in bridges]
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/util.py", line 266, in replaceControlChars
      if byte in range(0, 32) + [92, 127]:
  builtins.TypeError: unsupported operand type(s) for +: 'range' and 'list'

Test results changed as follows...

  before: FAILED (skips=109, failures=24, errors=220, successes=628)
  after:  FAILED (skips=109, failures=19, errors=221, successes=632)