Fix persistence tests
Nothing too interesting. Few files needed to be opened in bytes mode and a
deprecated os function replaced...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_persistent.py", line 53, in setUp
      fakeArgs = ['-c', os.path.join(os.getcwdu(), '..', 'bridgedb.conf')]
  builtins.AttributeError: module 'os' has no attribute 'getcwdu'

Test results changed as follows...

  before: FAILED (skips=109, failures=24, errors=349, successes=498)
  after:  FAILED (skips=109, failures=22, errors=318, successes=531)