Replace dict's iteritems with items
Python's methods for keys, values, and items now provide iterators so there is
no longer a separate iteritems method. This fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_metrics.py", line 108, in test_export
      metrics.export(pseudo_fh, 0)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/metrics.py", line 131, in export
      httpsLines = httpsMetrix.getMetrics()
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/metrics.py", line 235, in getMetrics
      for key, value in self.coldMetrics.iteritems():
  builtins.AttributeError: 'dict' object has no attribute 'iteritems'

This changes test results as follows...

  before: FAILED (skips=114, failures=15, errors=111, successes=745)
  after:  FAILED (skips=114, failures=15, errors=109, successes=747)