Forgot troubleshoting raise
Oops, this one is purely my bad. I negated this catch-all while troubleshooting
other test failures, but forgot to revert it afterward. This caused...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_bridges.py", line 1253, in test_Bridge_updateFromExtraInfoDescriptor_bad_signature_changed
      self.bridge.updateFromExtraInfoDescriptor(self.extrainfo)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1764, in updateFromExtraInfoDescriptor
      self._verifyExtraInfoSignature(descriptor)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1709, in _verifyExtraInfoSignature
      unpadded = removePKCS1Padding(decryptedBytes)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/crypto.py", line 261, in removePKCS1Padding
      raise PKCS1PaddingError("Couldn't find PKCS#1 separator byte!")
  bridgedb.crypto.PKCS1PaddingError: Couldn't find PKCS#1 separator byte!

Test results changed as follows...

  before: FAILED (skips=115, failures=27, errors=2, successes=840)
  after:  FAILED (skips=115, failures=27, errors=1, successes=841)