Syntax error due to long integer syntax
Python 3 no longer has a separate type for long integers (all numbers are
covered by ints). This fixes...

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 823, in loadByName
      return self.suiteFactory([self.findByName(name, recurse=recurse)])
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 702, in findByName
      __import__(name)
  builtins.SyntaxError: invalid syntax (test_bridgerequest.py, line 51)

Test results changed as follows...

  before: FAILED (skips=114, failures=14, errors=158, successes=695)
  after:  FAILED (skips=114, failures=14, errors=157, successes=700)