Drop unicode argument from gettext's install
Python 3.x is unicode by default and gettext doesn't have this argument any
longer so simply dropping it...

  https://docs.python.org/3/library/gettext.html#gettext.NullTranslations.install

This fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_translations.py", line 63, in test_getLocaleFromHTTPRequest_withLangParam_AcceptLanguage
      parsed = translations.getLocaleFromHTTPRequest(request)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/translations.py", line 90, in getLocaleFromHTTPRequest
      installTranslations(langs)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/translations.py", line 129, in installTranslations
      language.install(unicode=True)
  builtins.TypeError: install() got an unexpected keyword argument 'unicode'

Test results changed as follows...

  before: FAILED (skips=106, failures=16, errors=266, successes=416)
  after:  FAILED (skips=106, failures=17, errors=258, successes=423)