Discard attribute that's no longer used.
This fixes the following unit test:

[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/NullHypothesis/bridgedb/bridgedb/test/test_https.py", line 177, in test_content_security_policy
    headers = ''.join(self.br.response().info().headers)
builtins.AttributeError: 'HTTPMessage' object has no attribute 'headers'

bridgedb.test.test_https.HTTPTests.test_content_security_policy