Fix exec syntax
Updating the syntax for exec...

  https://docs.python.org/2.0/ref/exec.html
  https://docs.python.org/3/library/functions.html#exec

This fixes the following errors...

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 823, in loadByName
      return self.suiteFactory([self.findByName(name, recurse=recurse)])
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 702, in findByName
      __import__(name)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_https.py", line 41, in <module>
      from bridgedb.test.test_Tests import DynamicTestCaseMeta
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_Tests.py", line 29, in <module>
      from bridgedb.test import legacy_Tests as Tests
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/legacy_Tests.py", line 21, in <module>
      import bridgedb.main
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/main.py", line 24, in <module>
      from bridgedb import persistent
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/persistent.py", line 30, in <module>
      from bridgedb.configure import Conf
  builtins.SyntaxError: Missing parentheses in call to 'exec' (configure.py, line 85)

This changes test results as follows...

  before: FAILED (skips=6, failures=9, errors=194, successes=359)
  after:  FAILED (skips=103, failures=9, errors=189, successes=366)