Hashing requires bytes
Just another instance of bytes/unicode type conversion...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_https_distributor.py", line 153, in test_HTTPSDistributor_prepopulateRings_without_proxies
      [dist.insert(bridge) for bridge in self.bridges]
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_https_distributor.py", line 153, in <listcomp>
      [dist.insert(bridge) for bridge in self.bridges]
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/distributors/https/distributor.py", line 278, in insert
      self.hashring.insert(bridge)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/Bridges.py", line 606, in insert
      logging.debug("Inserting %s into hashring..." % bridge)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/bridges.py", line 1041, in __str__
      fingerprint = hashlib.sha1(fingerprint).hexdigest().upper()
  builtins.TypeError: Unicode-objects must be encoded before hashing

Test results changed as follows...

  before: FAILED (skips=114, failures=14, errors=157, successes=700)
  after:  FAILED (skips=114, failures=14, errors=149, successes=708)