Context manager class is now private
BridgeDB shouldn't use GeneratorContextManager, but if it does this class is
now under a new name...

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/twisted/trial/runner.py", line 823, in loadByName
      return self.suiteFactory([self.findByName(name, recurse=recurse)])
    ...
    File "./bridgedb/test/test_Storage.py", line 13, in <module>
      import bridgedb.Storage as Storage
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/Storage.py", line 11, in <module>
      from contextlib import GeneratorContextManager
  builtins.ImportError: cannot import name 'GeneratorContextManager'

This still doesn't change test outcome due to further Storage.py issues...

  before: FAILED (skips=1, failures=7, errors=49, successes=255)
  after:  FAILED (skips=1, failures=7, errors=49, successes=255)