Urllib removed its splithost function
Urllib's documentation said to avoid splithost, and the method was removed in
python 3....

  https://docs.python.org/2/library/urllib.html

This fixes...

  Traceback (most recent call last):
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/test/test_crypto.py", line 379, in test_verifyHostname_matching
      contextFactory = crypto.SSLVerifyingContextFactory(url)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/crypto.py", line 377, in __init__
      self.hostname = self.getHostnameFromURL(url)
    File "/home/atagar/Desktop/tor/bridgedb/bridgedb/crypto.py", line 413, in getHostnameFromURL
      hostname = urllib.splithost(urllib.splittype(url)[1])[0]
  builtins.AttributeError: module 'urllib' has no attribute 'splithost'

Test results changed as follows...

  before: FAILED (skips=114, failures=21, errors=57, successes=792)
  after:  FAILED (skips=114, failures=21, errors=55, successes=794)